a3_starter_code-main/projectfile/website/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from .forms import LoginForm,RegisterForm
#new imports:
from flask_login import login_user, login_required, logout_user
#from werkzeug.security import generate_password_hash,check_password_hash
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db

#create a blueprint
authbp = Blueprint('auth', __name__ )

@authbp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.name==uname))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(pwd)
            #create a new User model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('user.html', form=register, heading='Register')

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.name==user_name))
        #if there is no user with that name
        if user is None:
            error = 'Incorrect username'#could be a security risk to give this much info away
        #check the password - notice password hash function
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error = 'Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@authbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

a3_starter_code-main/projectfile/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Event, Booking
from . import db
from datetime import datetime

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    events = db.session.scalars(db.select(Event)).all()    
    return render_template('index.html', events=events)

@mainbp.route('/search')
def search():
    if request.args['search'] and request.args['search'] != "":
        print(request.args['search'])
        query = "%" + request.args['search'] + "%"
        events = db.session.scalars(db.select(Event).where(Event.description.like(query)))
        return render_template('index.html', events=events)
    else:
        return redirect(url_for('main.index'))


@mainbp.route('/ebks')
def ebks():
    bks = db.session.scalars(db.select(Booking)).all()    
    return render_template('userbooking.html', bks=bks)



@mainbp.route('/age-group')
def age_group(category):
    age_groups = {
        1: 'Age group 0-3',
        2: 'Age group 4-8',
        3: 'Age group 9-16'
    }

    if category in age_groups:
        return age_groups[category]
    else:
        return 'Invalid index'

a3_starter_code-main/projectfile/website/templates/Eventupdate.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Event Creation</title>
        
        <!--Rena Custom CSS-->
        <link href="style/test.css" rel="stylesheet">
        <!--From Bootstrap website CSS-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

  <body>
    <header>

      <!--Navigation bar-->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
           <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-lg-0" href="index.html">
            <img src="img/Logo.png" height="25" alt="KIDDOEVENT Logo"
            loading="lazy" />KIDDOEVENT
          </a>

          <!-- Toggle button -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>



            <!-- Collapsible wrapper -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
             
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="index.html">Home</a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="EventDetail.html">Event Listing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="Eventupdate.html">Create Event</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="history.html">Booking History</a>
              </li>
              <!-- Search fields -->
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search Events" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>

            </ul>
            <!-- Right links -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="#">Register</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">Login</a>
                  </li>
              </ul>
           </div>
          </div>

          
          <!-- Collapsible wrapper -->


        </div>
        <!-- Container wrapper -->
      </nav>

    

    </header>

  
        <main>

            <div class="jumbotron" style="background-image: url('img/Hero/BNE_1.jpg'); height: 200px;">
                <div class="container for-about">

            
          <div class="py-5 text-center" style="color: darkred; font-weight: bolder;  background-color: rgba(255, 255, 255, 0.7); opacity: 1;">
            <h2 style="font-weight: bold; ">KIDDOEVENT Event Creation</h2>
            <p class="lead" style="font-weight: bold;">
                To adevertise your event to public from us. Name your event and tell parents
                why they should join. Share special details that make your event differnt and 
                exciting.
            </p>
          </div>
        </div>
        </div>
      
        <!-- Table Reservation Form -->
        <section id="create-event" class="create-event">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-md-8 offset-md-2 text-center">
                        <p style="color:darkmagenta;">
                            Please complete all fields
                        </p>
                    </div>
                </div>

                <form action="" method="post" role="form">
                <div class="row">
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="EventName" class="form-label">Event Name </label>
                        <input type="text" name="name" class="form-control" id="EventName" placeholder="Event Name">
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="date" class="form-label">Event Date </label>
                        <input type="date" name="date" class="form-control" id="date" >
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="starttime" class="form-label">Event Start Time</label>
                        <input type="time" class="form-control" name="starttime" id="starttime" >
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="finishtime" class="form-label">Event Finish Time </label>
                        <input type="time" class="form-control" name="finishtime" id="finishtime" >
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="location" class="form-label">Event Location </label>
                        <input type="text" class="form-control" name="location" id="location" placeholder="Number and Road">
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="postcode" class="form-label">Event Location Postcode </label>
                        <input type="text" pattern="\d{4}" name="postcode" class="form-control" id="postcode" placeholder="4 digit postcode">
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="category" class="form-label">Event Category </label>
                        <input type="text" class="form-control" name="category" id="category" placeholder="Category">
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="maxticket" class="form-label">Number Of Event Ticket(s) </label>
                        <input type="number" class="form-control" name="maxticket" id="maxticket" placeholder="100">
                    </div>
                    <div class="col-lg-4 col-md-6 form-group">
                        <label for="price" class="form-label">Event Ticket Price </label>
                        <input type="number" class="form-control" name="price" id="price" placeholder="0">
                    </div>

                </div>
                <div class="form-group">
                    <label for="description" class="form-label">Event Description </label>
                    <textarea class="form-control" name="description" placeholder="Event Description"></textarea>
                </div>
                <div class="form-group">
                    <label for="formFile" class="form-label">Upload up to 10 images</label>
                    <input class="form-control" type="file" id="formFile" name="image[]" multiple accept="image/*" max="10">
                </div>
                <button type="submit" class="btn btn-primary float-right mt-3">Create Event Now</button>
                </form>
            </div>
        </section>
        <!-- End Table Reservation Form -->
        </main>
    
      
        <footer class="my-5 pt-5 text-body-secondary text-center text-small">
          <p class="mb-1">&copy; 2023–2023 KIDDOEVENT Pty Ltd</p>
          <ul class="list-inline">
            <li class="list-inline-item"><a href="#">Privacy</a></li>
            <li class="list-inline-item"><a href="#">Terms</a></li>
            <li class="list-inline-item"><a href="#">Support</a></li>
          </ul>
        </footer>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  
        </body>
      </html>
      

a3_starter_code-main/projectfile/website/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>KIDDOEVENT - The only site for your kids</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
   <!-- Header -->
   <header class="bg-light border-bottom">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">

            <!-- Your Travel App Name or Logo -->
            <a class="navbar-brand mt-2 mt-lg-0" href="/">
               <img src="{{url_for('static',filename='img/Logo.png')}}" height="25" alt="KIDDOEVENT Logo"
               loading="lazy" />KIDDOEVENT
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
               data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
               aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
               <div class="navbar-nav ml-auto">

                  <!-- Register/Login/Logout and welcome -->
                  {% if current_user.is_authenticated %}
                     <a class="nav-item nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                  {% else %}
                     <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                  {% endif %}

                  <a class="nav-item nav-link" href="{{ url_for('event.create') }}">Create Event</a>
                  <a class="nav-item nav-link" href="#">Bookings</a>
                  
               </div>
            </div>
         </div>
      </nav>
      <!-- flashes any messages to the user -->
      {% with messages = get_flashed_messages() %}
      {% if messages %} <!-- check if there are any messages -->
      <div class="container-fluid">
         <div class="row mt-3 mb-3">
            <div class="col-md-12">
            {% for message in messages %} <!--loop through the messages-->
            <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
            {% endfor %}
         </div>
      </div>
      </div>
      {% endif %}
      {% endwith %}
    
      {% block header %}

      {% endblock %}

   </header>
      
   {% block content %}

   {% endblock %}
   
    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; {{ year }}</span>
        </div>
    </footer> 
   </body>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

a3_starter_code-main/projectfile/website/templates/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KIDDOEVENT</title>

    <!-- Rena Custom CSS -->
    <link href="style/test.css" rel="stylesheet">
    <!-- From Bootstrap website CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
<header>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-lg-0" href="index.html">
                <img src="img/Logo.png" height="25" alt="KIDDOEVENT Logo"
                     loading="lazy"/>KIDDOEVENT
            </a>

            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="EventDetail.html">Event Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Eventupdate.html">Create Event</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="history.html">Booking History</a>
                    </li>
                </ul>
                <!-- Right links -->
                
            </div>
            <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
    </nav>

    <div class="jumbotron" style="background-image: url('img/Hero/BNE_1.jpg'); height: 200px;">
        <div class="container for-about"></div>
    </div>
</header>

<main>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <h3 class="fw-normal text-secondary fs-4 text-uppercase mb-4">Booking History</h3>

                <!-- List group for booking history -->
                <ul class="list-group">
                    <!-- Booking entry 1 -->
                    <li class="list-group-item">
                        <h5 class="card-title">Booking ID: 333456</h5>
                        <p class="card-text">Booking Date: 15/8/2023</p>
                        <p class="card-text">Booking Time: 15:31 pm</p>
                        <p class="card-text">Event Name: What is this?</p>
                        <p class="card-text">Event Category: Class</p>
                        <p class="card-text">Status: <span class="badge bg-primary">Consumed</span></p>
                        <p class="card-text">Number of Tickets: 4</p>
                        <p class="card-text">Total Amount: $80</p>
                        <a href="EventDetail.html" class="btn btn-primary">View Details</a>
                    </li>

                    <!-- Booking entry 2 -->
                    <li class="list-group-item">
                        <h5 class="card-title">Booking ID: 222123</h5>
                        <p class="card-text">Booking Date: 5/3/2023</p>
                        <p class="card-text">Booking Time: 16:36 pm</p>
                        <p class="card-text">Event Name: Explore nature</p>
                        <p class="card-text">Event Category: Discovery</p>
                        <p class="card-text">Status: <span class="badge bg-success">Confirmed</span></p>
                        <p class="card-text">Number of Tickets: 2</p>
                        <p class="card-text">Total Amount: $40</p>
                        <a href="EventDetail.html" class="btn btn-primary">View Details</a>
                    </li>

                    <!-- Booking entry 3 -->
                    <li class="list-group-item">
                        <h5 class="card-title">Booking ID: 111789</h5>
                        <p class="card-text">Booking Date: 19/3/2024</p>
                        <p class="card-text">Booking Time: 11:35 am</p>
                        <p class="card-text">Event Name: School holiday Party</p>
                        <p class="card-text">Event Category: Party</p>
                        <p class="card-text">Status: <span class="badge bg-danger">Cancelled</span></p>
                        <p class="card-text">Number of Tickets: 6</p>
                        <p class="card-text">Total Amount: $60</p>
                        <a href="EventDetail.html" class="btn btn-primary">Rebook</a>
                    </li>
                </ul>

                <!-- Pagination -->
                <nav>
                    <ul class="pagination justify-content-center mt-4">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</main>

<footer class="my-5 pt-5 text-body-secondary text-center text-small">
    <p class="mb-1">&copy; 2023–2023 KIDDOEVENT Pty Ltd</p>
    <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Privacy</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+I3kj7VbyVS1GssFO8SEHKjqEKZmONgC1f"
        crossorigin="anonymous"></script>
</body>
</html>

a3_starter_code-main/projectfile/website/templates/index.html
{% extends 'base.html' %}

{% block header %}


      <!-- Code from A2 for CarouslSlider -->
      <div id="CarouselSlider" class="carousel carousel-dark slide carousel-fade" data-bs-ride="carousel">
         <div class="carousel-indicators">
             <button type="button" data-bs-target="#CarouselSlider" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
             <button type="button" data-bs-target="#CarouselSlider" data-bs-slide-to="1" aria-label="Slide 2"></button>
             <button type="button" data-bs-target="#CarouselSlider" data-bs-slide-to="2" aria-label="Slide 3"></button>
             <button type="button" data-bs-target="#CarouselSlider" data-bs-slide-to="3" aria-label="Slide 3"></button>
         </div>
         <div class="carousel-inner">
             <div class="carousel-item active" data-bs-interval="5000">
                 <img src="{{url_for('static',filename='img/Hero/A_1.jpg')}}" class="d-block w-100" alt="Carousel One">
                 <div class="carousel-caption text-white d-none d-md-block col-6">
                     <h3 class="fs-1">Time to release kids energy?</h3>
                     <a href="#Eventsection" class="btn btn-warning mt-3">Click To Learn More</a>
                 </div>
             </div>
             <div class="carousel-item" data-bs-interval="5000">
                 <img src="{{url_for('static',filename='img/Hero/B_1.jpg')}}" class="d-block w-100" alt="Carousel Two">
                 <div class="carousel-caption text-white d-none d-md-block col-6">
                     <h3 class="fs-1">What is your local park like?</h3>
                     <a href="#Eventsection" class="btn btn-warning mt-3">Click To Learn More</a>
                 </div>
             </div>
             <div class="carousel-item" data-bs-interval="5000">
                 <img src="{{url_for('static',filename='img/Hero/C_1.jpg')}}" class="d-block w-100" alt="Carousel Three">
                 <div class="carousel-caption text-white d-none d-md-block col-6">
                     <h3 class="fs-1">Want to let them experiece more?</h3>
                     <a href="#Eventsection" class="btn btn-warning mt-3">Click To Learn More</a>
                 </div>
             </div>
             <div class="carousel-item" data-bs-interval="5000">
                 <img src="{{url_for('static',filename='img/Hero/D_1.jpg')}}" class="d-block w-100" alt="Carousel Three">
                 <div class="carousel-caption text-white d-none d-md-block col-6">
                     <h3 class="fs-1">Allow them to be future star?</h3>
                     <a href="#Eventsection" class="btn btn-warning mt-3">Click To Learn More</a>
                 </div>
             </div>
         </div>
         <button class="carousel-control-prev" type="button" data-bs-target="#CarouselSlider" data-bs-slide="prev">
             <span class="carousel-control-prev-icon" aria-hidden="true"></span>
             <span class="visually-hidden">Previous</span>
         </button>
         <button class="carousel-control-next" type="button" data-bs-target="#CarouselSlider" data-bs-slide="next">
             <span class="carousel-control-next-icon" aria-hidden="true"></span>
             <span class="visually-hidden">Next</span>
         </button>
       </div>



{% endblock %}

{% block content %}   

             <!--Jumbotron-->
             <div class="container">
               <div class="row justify-content-center mt-5 pb-4">
                  <div class="col-md-8">
                     <div class="card shadow p-5 mb-5 bg-light">
                        <a id="Eventsection"></a>
                        <h1 class="text-center mb-3">Let's find an event for you kid at KIDDOEVENT</h1>
      
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
                           <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
                           <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
                         </form>
                        
                     </div>
                  </div>
               </div>
            </div>

         <div class="card-group">
            {% for event in events %}
            <div class="card mx-3">
               <img class="card-img-top"
                  src="{{ event.image }}" alt="event picture">
               <div class="card-body">
                  <h5 class="card-title">Event Name: {{ event.name }}</h5>
                  <p class="card-text">Event Date: {{ event.date }}</p>
                  <p class="card-text">Event Description: {{ event.description }}</p>
                  <p class="card-text">Event Ticket Remain: {{ event.ticket_remain }}</p>
                  <p class="card-text">Event Ticket Price: $ {{ event.price }}</p>

               </div>
               <div class="card-footer"><a href="{{ url_for('event.show', id=event.id) }}" class ="btn btn-danger"> View Details </a></div>
               <div class="card-footer"><a href="{{ url_for('event.update', id=event.id) }}" class ="btn btn-danger"> Update Event </a></div>
            </div>
            {% endfor %}
         </div>
      </div>
{% endblock %}

a3_starter_code-main/projectfile/website/templates/user.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% block content %}

<div class="container-fluid">
<div class="page-header">
    <h4>{{ heading }}</h4>
</div>

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5">
  {{ render_form(form) }}
</div>

{% endblock %}

a3_starter_code-main/projectfile/website/templates/userbooking.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% block content %}

<div class="container-fluid">
<div class="page-header">
    <h4>{{ heading }}</h4>
</div>

<div class="card-group">
    {% for booking in bookings %}
    <div class="card mx-3">
        <div class="card-body">
          <h5 class="card-title">{{ booking.reference }}</h5>
          <p class="card-text">{{ booking.ticket }}</p>
          <p class="card-text">{{ booking.paymentdate }}</p>
          <p class="card-text">{{ booking.amount }}</p>
       </div>
    </div>
    {% endfor %}
 </div>

{% endblock %}